using System;
using System.Collections.Generic;
using System.Text;

namespace ImageTool.Imaging;

// Ghi ICC profile RGB toi gian (v2, display-class, PCS = XYZ D50) cho 1 khong gian mau quen thuoc
// (sRGB/AdobeRGB/Rec2020/DisplayP3). Dung de NHUNG vao file xuat -> mau hien thi dung tren web/may khac.
// Cau truc: header 128 byte + bang tag + du lieu cac tag bat buoc:
//   desc (mo ta), wtpt (white point D50), rXYZ/gXYZ/bXYZ (colorant), rTRC/gTRC/bTRC (gamma curve), cprt.
// Doi xung voi IccProfileReader -> round-trip test duoc (build -> TryReadRgbToXyzD65 -> MatchSpace).
public static class IccProfileWriter
{
    // White point D50 (PCS chuan ICC), XYZ.
    private static readonly float[] D50 = { 0.96422f, 1.00000f, 0.82521f };

    // Gamma xap xi cho TRC (curveType 1 tham so): sRGB ~2.2 (du dung cho nhung; doc-lai khong dung TRC).
    private static float GammaOf(ColorSpaces.Space s) => s switch
    {
        ColorSpaces.Space.AdobeRgb => 2.2f,
        ColorSpaces.Space.Rec2020 => 2.4f,
        _ => 2.2f, // sRGB/P3 xap xi 2.2 (TRC chinh xac la piecewise, nhung gamma du cho profile nhung).
    };

    public static string DescriptionOf(ColorSpaces.Space s) => s switch
    {
        ColorSpaces.Space.AdobeRgb => "Adobe RGB (1998) compatible",
        ColorSpaces.Space.Rec2020 => "Rec. 2020 compatible",
        ColorSpaces.Space.DisplayP3 => "Display P3 compatible",
        _ => "sRGB IEC61966-2.1 compatible",
    };

    // Build day du byte ICC cho khong gian s.
    public static byte[] Build(ColorSpaces.Space s)
    {
        float[] m = ColorSpaces.RgbToXyzD50(s); // RGB->XYZ D50, row-major
        string desc = DescriptionOf(s);
        float gamma = GammaOf(s);

        // Cac tag (sig + payload).
        var tags = new List<(string sig, byte[] data)>();
        tags.Add(("desc", BuildTextDescription(desc)));
        tags.Add(("wtpt", BuildXyzTag(D50[0], D50[1], D50[2])));
        // Cot r/g/b cua ma tran (X,Y,Z theo cot).
        tags.Add(("rXYZ", BuildXyzTag(m[0], m[3], m[6])));
        tags.Add(("gXYZ", BuildXyzTag(m[1], m[4], m[7])));
        tags.Add(("bXYZ", BuildXyzTag(m[2], m[5], m[8])));
        byte[] trc = BuildCurveTag(gamma);
        tags.Add(("rTRC", trc));
        tags.Add(("gTRC", trc));
        tags.Add(("bTRC", trc));
        tags.Add(("cprt", BuildTextTag("CC0 / generated by ImageTool")));

        return Assemble(tags);
    }

    // === Ghep header + bang tag + du lieu (tat ca big-endian, padding 4 byte) ===
    private static byte[] Assemble(List<(string sig, byte[] data)> tags)
    {
        int tableStart = 128;
        int tableSize = 4 + tags.Count * 12;     // count(4) + entries
        int dataStart = Align4(tableStart + tableSize);

        // Tinh offset + size cho tung tag.
        var offsets = new int[tags.Count];
        var sizes = new int[tags.Count];
        int cur = dataStart;
        for (int i = 0; i < tags.Count; i++)
        {
            offsets[i] = cur;
            sizes[i] = tags[i].data.Length;
            cur = Align4(cur + sizes[i]);
        }
        int total = cur;

        var b = new byte[total];
        // --- Header (128 byte) ---
        WriteU32(b, 0, total);                    // profile size
        WriteAscii(b, 4, "imgt");                 // preferred CMM (tuy y)
        WriteU32(b, 8, 0x02100000);               // version 2.1.0
        WriteAscii(b, 12, "mntr");                // device class = display
        WriteAscii(b, 16, "RGB ");                // color space
        WriteAscii(b, 20, "XYZ ");                // PCS
        // 24..35: date/time (de 0)
        WriteAscii(b, 36, "acsp");                // signature bat buoc
        // 40..43 platform, 44..47 flags... de 0.
        WriteU32(b, 64, 0);                        // rendering intent = perceptual
        // illuminant D50 trong header (68..79): s15Fixed16 X,Y,Z
        WriteS15Fixed16(b, 68, D50[0]);
        WriteS15Fixed16(b, 72, D50[1]);
        WriteS15Fixed16(b, 76, D50[2]);

        // --- Tag table ---
        WriteU32(b, tableStart, tags.Count);
        for (int i = 0; i < tags.Count; i++)
        {
            int e = tableStart + 4 + i * 12;
            WriteAscii(b, e, tags[i].sig);
            WriteU32(b, e + 4, offsets[i]);
            WriteU32(b, e + 8, sizes[i]);
        }

        // --- Tag data ---
        for (int i = 0; i < tags.Count; i++)
            Array.Copy(tags[i].data, 0, b, offsets[i], tags[i].data.Length);

        return b;
    }

    // 'XYZ ' tag: type(4) + reserved(4) + 3 s15Fixed16.
    private static byte[] BuildXyzTag(float x, float y, float z)
    {
        var d = new byte[20];
        WriteAscii(d, 0, "XYZ ");
        WriteS15Fixed16(d, 8, x);
        WriteS15Fixed16(d, 12, y);
        WriteS15Fixed16(d, 16, z);
        return d;
    }

    // 'curv' tag voi 1 entry = gamma (u8Fixed8). type(4)+reserved(4)+count(4)+ count*u16.
    private static byte[] BuildCurveTag(float gamma)
    {
        var d = new byte[12 + 2];
        WriteAscii(d, 0, "curv");
        WriteU32(d, 8, 1);                        // 1 entry => gamma
        int g = (int)MathF.Round(gamma * 256f);   // u8Fixed8
        d[12] = (byte)(g >> 8); d[13] = (byte)(g & 0xFF);
        return d;
    }

    // 'desc' textDescriptionType (v2): type(4)+reserved(4)+count(4)+ASCII(count, NUL-term)
    //   + 4 (unicode lang) + 4 (unicode count=0) + 67 byte scriptcode block (de 0).
    private static byte[] BuildTextDescription(string text)
    {
        var ascii = Encoding.ASCII.GetBytes(text);
        int count = ascii.Length + 1;             // gom NUL
        int len = 12 + count + 4 + 4 + 3 + 67;    // header + ascii + uni(8) + scriptcode(2+1+67)
        var d = new byte[len];
        WriteAscii(d, 0, "desc");
        WriteU32(d, 8, count);
        Array.Copy(ascii, 0, d, 12, ascii.Length); // NUL tu de 0
        // phan unicode + scriptcode de 0 (hop le, nhieu profile that lam vay).
        return d;
    }

    // 'text' tag (v2 cprt): type(4)+reserved(4)+ASCII(NUL-term).
    private static byte[] BuildTextTag(string text)
    {
        var ascii = Encoding.ASCII.GetBytes(text);
        var d = new byte[8 + ascii.Length + 1];
        WriteAscii(d, 0, "text");
        Array.Copy(ascii, 0, d, 8, ascii.Length);
        return d;
    }

    private static int Align4(int n) => (n + 3) & ~3;

    private static void WriteU32(byte[] b, int o, int v)
    { b[o] = (byte)(v >> 24); b[o + 1] = (byte)(v >> 16); b[o + 2] = (byte)(v >> 8); b[o + 3] = (byte)v; }

    private static void WriteS15Fixed16(byte[] b, int o, float v)
        => WriteU32(b, o, (int)MathF.Round(v * 65536f));

    private static void WriteAscii(byte[] b, int o, string s)
    { var a = Encoding.ASCII.GetBytes(s); Array.Copy(a, 0, b, o, a.Length); }
}
